[package]
name = "moa"
version = "0.1.0"
description = "Desktop bookkeeping application"
authors = ["ekuinox"]
license = "MIT"
edition = "2024"
rust-version = "1.95.0"
default-run = "moa"

[lib]
name = "moa_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
specta = { version = "=2.0.0-rc.24" }
specta-typescript = { version = "=0.0.11" }
sqlx = { version = "0.8.6", default-features = false, features = ["macros", "migrate", "runtime-tokio", "sqlite"] }
tauri = { version = "2", features = [] }
tauri-specta = { version = "=2.0.0-rc.24", features = ["typescript"] }
